owners:
  - Chicken Bütt

status:
  avatar: CID_017_Athena_Commando_M
  status: "\U0001f60d\U0001F975\U0001F449 https://ezfn.net\U0001F975"

commands:
  prefix:
    - "!"
    - /
  case_insensitive: true
  only_owners: true

friends:
  invite_on_added: false
  accept_all_requests: true
  decline_all_requests: false
  invite_on_startup: false
  add_on_removed: false

party:
  dont_leave_if_owner_in_party: true
  join_on_invite: true
  join_if_party_is_empty: true
  
  add_all_members_on_join: false

turn_on: true
